import { useState } from 'react';
import { Card, PageHero, Section, StatusPill } from '../components/Primitives';
import { ResumeTailorPanel, RoleMatchScorer } from '../components/CareerCommand';
import { analyzeResume, resumeVersions } from '../data/resumeContent';
import { useAsyncAction } from '../hooks/useAsyncAction';
import { apiAnalyzeResume } from '../lib/api';

export default function ResumeLab(){ const [text,setText]=useState(''); const [version,setVersion]=useState(resumeVersions[0]); const [targetLane,setTargetLane]=useState('CRM / Lifecycle Marketing'); const [analysis,setAnalysis]=useState(null); const [saved,setSaved]=useState([]); const { run, loading, usedFallback } = useAsyncAction(); async function analyze(){ const result = await run(apiAnalyzeResume, (input)=>({...analyzeResume(input.resumeText, input.targetLane), resumeVersion: input.resumeVersion}), { resumeText:text, resumeVersion:version, targetLane }); setAnalysis(result); } return <><PageHero eyebrow="Resume Lab" title="Extract proof. Tailor fast." subtitle="Upload or paste a resume, find reusable proof blocks, and create role-specific versions without turning this into a document editor." />
<Section title="1. Upload / Paste Resume" subtitle="File input is visual for now. Paste text is the functional fallback."><Card accent="yellow"><div className="form-grid"><input type="file" accept=".pdf,.doc,.docx,.txt"/><select value={version} onChange={e=>setVersion(e.target.value)}>{resumeVersions.map(v=><option key={v}>{v}</option>)}</select></div><textarea value={text} onChange={e=>setText(e.target.value)} placeholder="Paste resume text here..."/><button className="button primary" onClick={analyze} disabled={loading}>{loading ? 'Analyzing resume…' : 'Analyze Resume'}</button>{usedFallback&&analysis&&<span className="muted">Using local fallback.</span>}</Card></Section>
{analysis&&<><Section title="2. Analyze Resume" subtitle="Mock local analysis now; structured for future AI integration."><RoleMatchScorer score={analysis.roleMatch}/></Section><Section title="3. Strengths Extracted"><div className="card-grid four">{analysis.strengths.map(s=><Card key={s}><StatusPill tone="lime">Strength</StatusPill><h3>{s}</h3></Card>)}</div></Section><Section title="4. Quantified Achievements"><div className="card-grid two">{analysis.quantifiedAchievements.map(a=><Card key={a.original}><p><b>Original:</b> {a.original}</p><p><b>Improved:</b> {a.improved}</p><p><b>Metric:</b> {a.metric}</p></Card>)}</div></Section><Section title="5. Weak Bullet Fixes"><div className="card-grid two">{analysis.weakBullets.map(w=><Card key={w.bullet}><p><b>{w.bullet}</b></p><p>{w.issue}</p><div className="talking-point">Fix: <b>{w.fix}</b></div></Card>)}</div></Section><Section title="6. Tailored Versions"><div className="card-grid three">{Object.entries(analysis.tailoredSummaries).map(([k,v])=><Card key={k}><h3>{k}</h3><p>{v}</p><button className="button secondary">Save version</button></Card>)}</div></Section><Section title="7. Bullet Swap Bank"><div className="card-grid three">{analysis.bulletSwaps.map(b=><Card key={b.after}><span className="tag">{b.targetLane}</span><p>{b.before}</p><div className="talking-point">{b.after}</div><p>{b.reason}</p></Card>)}</div></Section><Section title="Resume-to-Job Tailor"><ResumeTailorPanel resume={analysis}/></Section><Section title="8. Save Resume Version"><Card><button className="button primary" onClick={()=>setSaved([...saved,version])}>Save {version}</button><p>Saved versions: {saved.join(', ') || 'None yet'}</p></Card></Section></>}
</> }
