import { useState } from 'react';
import { Link, useLocation } from 'react-router-dom';
import { Card, StatusPill } from './Primitives';
import { coachModes, generateCoachAction, generateOutreachMessage, generateRecoveryRep, scoreJob, tailorResumeToJob } from '../data/coachActions';
import { roleLanes, sources } from '../data/jobCaptureData';
import { resumeVersions } from '../data/resumeContent';
import { proofLibrary } from '../data/proofLibrary';
import { interviewQuestions, generateInterviewAnswer } from '../data/interviewContent';

export function RoleMatchScorer({ score = {} }) {
 const overall = score.matchScore || score.overall || 86;
 const label = overall >= 85 ? 'Attack now' : overall >= 70 ? 'Worth applying with tailoring' : overall >= 55 ? 'Save only if strategic' : 'Skip unless relationship leverage exists';
 const cats = [['Skill Match',score.skillMatch],['Proof Match',score.proofMatch],['Logistics Fit',score.logisticsFit],['Strategic Value',score.strategicValue]];
 return <div className="role-score"><div className="score-circle"><strong>{overall}</strong><span>{label}</span></div><div className="score-detail"><StatusPill tone={overall >= 85 ? 'lime' : 'yellow'}>{score.applicationDifficulty || 'Medium'} difficulty</StatusPill><p>{score.reason || 'Proof, skills, and next action are clear enough to move.'}</p>{cats.map(([k,v])=><div className="score-row" key={k}><span>{k}</span><div><i style={{width:`${v || 80}%`}} /></div><strong>{v || 80}</strong></div>)}<b>Next action: {score.nextAction || 'Tailor proof and apply.'}</b></div></div>;
}
export function ResumeTailorPanel({ job = {}, resume = {} }) { const t = tailorResumeToJob(resume, job); return <Card accent="cyan" className="tailor-panel"><span className="tag">Resume-to-Job Tailor</span><h3>{t.selectedJob}</h3><p><b>Resume:</b> {t.selectedResumeVersion}</p><div className="chip-row">{t.jobKeywords.map(k=><span className="pill" key={k}>{k}</span>)}</div><p><b>Missing:</b> {t.missingKeywords.join(', ')}</p><h3>{t.suggestedHeadline}</h3><p>{t.suggestedSummary}</p>{t.bulletChanges.map(b=><div className="swap" key={b.before}><small>Before</small><p>{b.before}</p><small>After</small><p><b>{b.after}</b></p><small>{b.why}</small></div>)}<div className="talking-point">Recommended proof card: <b>{t.recommendedProofCard}</b></div><ul>{t.applicationNotes.map(n=><li key={n}>{n}</li>)}</ul></Card>; }
export function JobCaptureModal({ inline=false }) { const [open,setOpen]=useState(inline); const [input,setInput]=useState({lane:roleLanes[3], source:sources[0]}); const [result,setResult]=useState(null); const body=<div className="capture-body"><div className="form-grid"><input placeholder="Role title" onChange={e=>setInput({...input,role:e.target.value})}/><input placeholder="Company" onChange={e=>setInput({...input,company:e.target.value})}/><select onChange={e=>setInput({...input,lane:e.target.value})}>{roleLanes.map(l=><option key={l}>{l}</option>)}</select><select onChange={e=>setInput({...input,source:e.target.value})}>{sources.map(s=><option key={s}>{s}</option>)}</select><input placeholder="Job URL"/><input placeholder="Location / remote / commute notes" onChange={e=>setInput({...input,location:e.target.value})}/><input placeholder="Salary range optional"/><input type="date"/></div><textarea placeholder="Paste job description" onChange={e=>setInput({...input,description:e.target.value})}/><button className="button primary" onClick={()=>setResult(scoreJob(input))}>Score Job</button>{result&&<><RoleMatchScorer score={result}/><div className="card-grid two"><Card><h3>Keywords & proof</h3><p>{result.keywords.join(', ')}</p><p><b>Proof:</b> {result.recommendedProofAssets.join(' · ')}</p><p><b>Resume:</b> {result.recommendedResumeVersion}</p><p><b>Today’s Rep:</b> {result.suggestedRep}</p></Card><ResumeTailorPanel job={input}/></div></>}</div>; if(inline) return body; return <><button className="button primary" onClick={()=>setOpen(true)}>Capture Job</button>{open&&<div className="drawer-backdrop"><div className="coach-drawer wide"><button className="button ghost" onClick={()=>setOpen(false)}>Close</button><h2>Capture Job</h2>{body}</div></div>}</>; }
export function OutreachGenerator(){ const [input,setInput]=useState({audience:'Hiring Manager',tone:'direct'}); const [out,setOut]=useState(null); return <Card accent="purple"><span className="tag">Outreach Generator</span><div className="form-grid"><select onChange={e=>setInput({...input,audience:e.target.value})}>{['Alumni','Former coworker','Former manager','Hiring manager','Recruiter','Weak tie','Warm intro request','Post-application follow-up','Post-interview thank you','Informational interview ask'].map(x=><option key={x}>{x}</option>)}</select>{['Contact name','Company','Role','Context','Desired outcome'].map(x=><input key={x} placeholder={x} onChange={e=>setInput({...input,[x.toLowerCase().split(' ')[0]]:e.target.value})}/>)}</div><button className="button primary" onClick={()=>setOut(generateOutreachMessage(input))}>Generate Message</button>{out&&<div className="output-card"><h3>{out.subject}</h3><p>{out.message}</p><small>{out.message.split(/\s+/).length} words</small><p><b>Follow-up:</b> {out.followUp}</p><button className="button secondary">Copy</button><button className="button ghost">Save to Outreach Tracker</button></div>}</Card> }
export function InterviewAnswerBuilder(){ const [proof,setProof]=useState(proofLibrary[0]); const [q,setQ]=useState(interviewQuestions[0]); const [ans,setAns]=useState(''); const [count,setCount]=useState(0); return <Card accent="yellow"><span className="tag">Answer Builder</span><div className="form-grid"><select onChange={e=>setQ(e.target.value)}>{interviewQuestions.map(x=><option key={x}>{x}</option>)}</select><select onChange={e=>setProof(proofLibrary.find(p=>p.title===e.target.value))}>{proofLibrary.map(p=><option key={p.id}>{p.title}</option>)}</select><select>{roleLanes.map(l=><option key={l}>{l}</option>)}</select></div><button className="button primary" onClick={()=>setAns(generateInterviewAnswer(q,proof).fullAnswer)}>Generate Point → Evidence → Judgment</button><textarea value={ans} onChange={e=>setAns(e.target.value)} placeholder="Generated answer appears here"/><div className="button-row"><button className="button secondary">Start 2:00 timer</button><button className="button primary" onClick={()=>setCount(count+1)}>Mark Practiced ({count})</button><select><option>Confidence 3/5</option><option>Confidence 4/5</option></select></div></Card> }
export function ProofCard({ project }){ return <Card className="project-card"><h3>{project.title}</h3><dl>{['problem','action','system','metric','roleRelevance','interviewTalkingPoint'].map(k=><div key={k}><dt>{k}</dt><dd>{project[k]}</dd></div>)}</dl><div className="talking-point">Resume bullet: <b>{project.resumeBullet}</b></div><div className="button-row"><button className="button secondary">Copy resume bullet</button><button className="button ghost">Use in interview answer</button><button className="button ghost">Use in outreach</button><button className="button primary">Add to application</button></div></Card> }
export function PipelineCommandCenter(){ const widgets=[['Follow-ups due','3','You have 3 open loops.','Send one follow-up today.'],['Applications this week','12','Base habit is active.','Convert one saved role.'],['Outreach this week','8','Leverage layer warming.','Send one warm follow-up.'],['Interviews scheduled','2','Conversion stage is live.','Practice one answer.'],['Bottleneck','Saved roles not converted','You are collecting faster than applying.','Run one Application Rep.'],['Best next action','CRM Specialist','High match and deadline close.','Tailor summary now.'],['Stale opportunities','2','No action in 7+ days.','Follow up, close, or refresh.'],['Options created','7','Pressure is decreasing.','Create one more option.'],['Weekly XP','420','60% to target.','Claim 50 XP today.'],['Conversion by stage','Saved → Applied: 54%','Tailoring speed is the constraint.','Reuse bullet swaps.']]; return <div className="card-grid five">{widgets.map(w=><Card key={w[0]}><span className="tag">{w[0]}</span><h3>{w[1]}</h3><p>{w[2]}</p><b>Next: {w[3]}</b></Card>)}</div> }
export function RecoveryModeCard(){ const [rep,setRep]=useState(null); return <Card accent="coral"><h3>Recovery Mode</h3><button className="button primary" onClick={()=>setRep(generateRecoveryRep())}>Too Tired: Give Me The Smallest Useful Rep</button>{rep&&<div className="output-card"><h3>{rep.title}</h3><p>{rep.why}</p><ol>{rep.steps.map(s=><li key={s}>{s}</li>)}</ol><p><b>{rep.timeEstimate}</b> · +{rep.xp} XP</p><p>{rep.completionCriteria}</p></div>}</Card> }
export function AskCoachDrawer(){ const [open,setOpen]=useState(false); const [mode,setMode]=useState(coachModes[0]); const [ctx,setCtx]=useState(''); const [out,setOut]=useState(null); const loc=useLocation(); return <><button className="button secondary ask-top" onClick={()=>setOpen(true)}>Ask Coach</button><button className="floating-coach" onClick={()=>setOpen(true)}>Ask Coach</button>{open&&<div className="drawer-backdrop"><aside className="coach-drawer"><button className="button ghost" onClick={()=>setOpen(false)}>Close</button><span className="tag">Current page: {loc.pathname}</span><h2>Structured Action Coach</h2><select value={mode} onChange={e=>setMode(e.target.value)}>{coachModes.map(m=><option key={m}>{m}</option>)}</select><textarea placeholder="Optional context: bullet, role, job description, interview question..." value={ctx} onChange={e=>setCtx(e.target.value)}/><button className="button primary" onClick={()=>setOut(generateCoachAction(mode,ctx))}>Generate Action</button>{out&&<div className="output-card"><h3>{out.answer}</h3><p>{out.reason}</p><p><b>Next rep:</b> {out.nextRep}</p><p>{out.timeEstimate} · +{out.xp} XP</p>{out.strongerVersion&&<p><b>Rewrite:</b> {out.strongerVersion}</p>}{out.score&&<RoleMatchScorer score={out.score}/>}<div className="button-row"><button className="button secondary">Copy</button><button className="button ghost">Save to tracker</button><button className="button ghost">Save to proof library</button><button className="button primary">Use as Today’s Rep</button></div>{out.relatedPage&&<Link className="button secondary full" to={out.relatedPage}>{out.suggestedAction}</Link>}</div>}</aside></div>}</> }
